### ISSUE TITLE
App crashes while clicking on delete list 

### ISSUE THREAD

**Issue by pzdawood** [woefe/ShoppingList#30] opened 2018-05-16 18:12 UTC
### Actual behaviour
When i open the shopping list app and add shopping list by clicking on plus sign at the bottom of left side.then I click on option botton and select delete list option and delete all lists . I again go to options blog and click on delete list option.After clicking on delete option app crashes.
### How to reproduce
* Open the shopping list app.
* Add shopping list by clicking on plus sign.
* Click on options botton at the top.
* select delete list option and delete shopping lists.
* Again click on options botton.
* Click on delete list option.
* After clicking on delete list option app crashes.
* Browser: shopping list.
* Version:0.9.0
* Operating system:7.1.2
### Recording of the bug:
https://youtu.be/0VRs6d1EmDU

**Comment by woefe** [comment] 2018-05-23 20:17
Duplicate of #19 and #26. It is fixed in v0.10.0

**Closed by woefe** 2018-05-23 20:17 UTC
