### ISSUE TITLE
The application is broken after selecting the folder in (file location)

### ISSUE THREAD

**Issue by Explorer00** [woefe/ShoppingList#33] opened 2018-05-29 13:07 UTC
#### expected behavior
After selecting the folder in the feature (file location) then back to the main page of the application, this application should not be damaged.

#### Real behavior
After the user selects the folder in the feature (file location) and the user returns to the application main page suddenly the application is broken.

#### How to reproduce
- Download app in f-droid.
- Run the app.
- Create a new list and click ok.
- Next go to settings.
- select location feature.
- select a folder and click ok.
- then back to the app's main page.
- suddenly the application is broken.
- Browser: Shopping List v0.10.0
- Operating system: xiomi redmi 4A, Android v6.0.1

#### Recording Of The Bug
https://youtu.be/EzshbwNw7nY

**Comment by woefe** [comment] 2018-05-29 14:52
Thanks for the Video. It is probably a duplicate of #32. It was fixed in `v0.10.1`. Feel free to reopen, if not.

**Closed by woefe** 2018-05-29 14:52 UTC
