### ISSUE TITLE
Manual sorting of items results in items overlaping

### ISSUE THREAD

**Issue by jghq** [woefe/ShoppingList#16] opened 2018-03-10 22:13 UTC
Workaround is to switch to a different list and back.

In the example below, Item 2 was moved up and now covers Item 1.

Edit: Only an issue on Kitkat, not Nougat, so probably not a priority.

![overlap](https://user-images.githubusercontent.com/31827586/37247251-46a84724-24b0-11e8-8888-34233ac0d02f.png)

**Comment by woefe** [comment] 2018-03-18 15:29
I encountered this problem myself sometimes. But I cannot reliably reproduce it, unfortunately. It is a bug in the ListView implementation that appears because Android recycles the ListView items when scrolling/reordering items. Item1 is actually there, but not visible (i.e. it is not properly re-initialized after recycling).

You can usually work around the problem by moving up and down again.

I basically copied the implementation form a Google sample project. It is not perfect and better alternatives exist in Android today, e.g. RecyclerView. I will look into it when I have more time. For now other issues will have higher priority.

**Comment by woefe** [comment] 2018-04-30 07:15
Fixed in bb1bcc4. If it's not fixed in the next release, feel free to reopen this issue.

**Closed by woefe** 2018-04-30 07:15 UTC
Labels: bug
