### ISSUE TITLE
[Feature request] Add option, to rename a shopping list

### ISSUE THREAD

**Issue by ronidee** [woefe/ShoppingList#60] opened 2020-01-12 20:33 UTC
An option to rename a shopping list would be good.

Is this app still being maintained? Would a pullrequest implementing this feature be merged?

**Comment by salim-b** [comment] 2020-01-13 20:14
This seems to be a duplicate of #6

**Comment by woefe** [comment] 2020-01-13 21:03
Closed as duplicate of #6.

PRs are welcome. I'm planning the next minor release for March. I hope I find the time to go over pending PRs by then :sweat_smile:

**Closed by woefe** 2020-01-13 21:03 UTC

**Comment by ronidee** [comment] 2020-02-05 16:25
okay good to know. unfortunately I'm in middle of exams atm, but after that I'll definitely do a PR. I use the app ~weekly and really miss that feature myself so... ^^
